// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dilsjiojwuvrrthisper.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbHNqaW9qd3V2cnJ0aGlzcGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDE2NjIsImV4cCI6MjA3MzAxNzY2Mn0.auIWZ9O6ZMeeCBieci5wiNg_d3xrmKvSBWOhv8X8cIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});