// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpxdsswmeejogwhtcqyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhweGRzc3dtZWVqb2d3aHRjcXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODYyNzcsImV4cCI6MjA2OTI2MjI3N30.B2dUreJRytWiUnIYCoVJk3VyGPzZeSOiIqH3cZus8Vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});