// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbfnjgjdknfyxvefyseq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZm5qZ2pka25meXh2ZWZ5c2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTExOTUsImV4cCI6MjA3MjAyNzE5NX0.25eoS3Yaf4lpjyqVn9jAtKg60lcRCeJG_ESkhjbLSN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});